


// HERE IS THE DETAILED EXAMPLE SHOWING HOW TO ENCAPSULATE A CALLBACK-BASED
// FUNCTION TO MAKE A 'SYNCHRONOUS' FUNCTION
var getJSON=function(url){
    var callback = yield (Thread.Resume); //ASK FOR A CALLBACK THAT CAN RESUME THE CURRENT THREAD
    $.getJSON(url, callback);             //THIS CURRENT THREAD WILL RESUME WHEN callback IS CALLED
    yield (Thread.Suspend);               //INDICATE THE CURRENT THREAD WILL SUSPEND UNTIL RESUME CALLBACK IS EXECUTED
};//method

