


// HERE IS THE DETAILED EXAMPLE SHOWING HOW TO ENCAPSULATE A CALLBACK-BASED
// FUNCTION TO A 'SYNCHRONOUS' FUNCTION
var getJSON=function(url){
	//JSON CALLS REQUIRE A GLOBAL FUNCTION
	var callback = yield (Thread.Resume);	//ASK FOR A CALLBACK FROM THE GENERATOR
	$.getJSON(url, callback);				//THIS THREAD WILL RESUME WHEN callback IS CALLED
	yield (Thread.Suspend);  				//TELL THE GENERATOR THIS FUNCTION HAS NOTHING LEFT TO DO
};//method

